module.exports = {
  publicPath: process.env.CI_JOB_NAME === 'pages' ? '/joinpeertube/' : '',

  pluginOptions: {
    prerenderSpa: {
      registry: undefined,
      renderRoutes: [
        '/',
        '/help',
        '/news',
        '/instances',
        '/hall-of-fame',
        '/faq',
        '/content-selections',
        '/en_US',
        '/en_US/help',
        '/en_US/news',
        '/en_US/instances',
        '/en_US/hall-of-fame',
        '/en_US/faq',
        '/en_US/content-selections',
        '/fr_FR',
        '/fr_FR/help',
        '/fr_FR/news',
        '/fr_FR/instances',
        '/fr_FR/hall-of-fame',
        '/fr_FR/faq',
        '/fr_FR/content-selections',
        '/de',
        '/de/help',
        '/de/news',
        '/de/instances',
        '/de/hall-of-fame',
        '/de/faq',
        '/de/content-selections',
        '/es',
        '/es/help',
        '/es/news',
        '/es/instances',
        '/es/hall-of-fame',
        '/es/faq',
        '/es/content-selections',
        '/it',
        '/it/help',
        '/it/news',
        '/it/instances',
        '/it/hall-of-fame',
        '/it/faq',
        '/it/content-selections',
        '/pl',
        '/pl/help',
        '/pl/news',
        '/pl/instances',
        '/pl/hall-of-fame',
        '/pl/faq',
        '/pl/content-selections',
        '/pt_BR',
        '/pt_BR/help',
        '/pt_BR/news',
        '/pt_BR/instances',
        '/pt_BR/hall-of-fame',
        '/pt_BR/faq',
        '/pt_BR/content-selections',
        '/ru',
        '/ru/help',
        '/ru/news',
        '/ru/instances',
        '/ru/hall-of-fame',
        '/ru/faq',
        '/ru/content-selections',
        '/sv',
        '/sv/help',
        '/sv/news',
        '/sv/instances',
        '/sv/hall-of-fame',
        '/sv/faq',
        '/sv/content-selections',
        '/en',
        '/en/help',
        '/en/news',
        '/en/instances',
        '/en/hall-of-fame',
        '/en/faq',
        '/en/content-selections',
        '/fr',
        '/fr/help',
        '/fr/news',
        '/fr/instances',
        '/fr/hall-of-fame',
        '/fr/faq',
        '/fr/content-selections',
        '/pt',
        '/pt/help',
        '/pt/news',
        '/pt/instances',
        '/pt/hall-of-fame',
        '/pt/faq',
        '/pt/content-selections'
      ],
      useRenderEvent: true,
      headless: true,
      onlyProduction: true
    }
  }
}
