[[Languages.de.menu.switchlang]]
  name = "English"
  identifier = ""
  weight = 4
  url = "en"

[[Languages.de.menu.switchlang]]
  name = "Français"
  identifier = ""
  weight = 4
  url = "fr"

[[Languages.de.menu.switchlang]]
  name = "Nederlands"
  identifier = ""
  weight = 4
  url = "nl"

[Languages.de]
languageCode = "de"
title = "JoinPeerTube"
weight = 1

[[Languages.de.menu.main]]
name = "FAQ"
identifier = "faq"
weight = 2
title = "FAQ"
url = "/de/faq/"

[[Languages.de.menu.main]]
name = "Unterstützung"
weight = 3
identifier = ""
url = "https://framacolibri.org/c/peertube"

[[Languages.de.menu.main]]
name = "Dokumentation"
weight = 4
identifier = ""
url = "https://docs.joinpeertube.org/"

[[Languages.de.menu.main]]
name = "Quellcode"
weight = 5
identifier = ""
url = "https://github.com/Chocobozzz/PeerTube"

[[Languages.de.menu.main]]
name = "Instanzen"
weight = 6
identifier = ""
url = "https://instances.joinpeertube.org"

[[Languages.de.menu.main]]
name = "Ehrenliste"
identifier = "hof"
weight = 7
title = "Hall of fame"
url = "/de/hall-of-fame/"
