[[Languages.eo.menu.switchlang]]
  name = "Deutsch"
  identifier = ""
  weight = 4
  url = "de"

[[Languages.eo.menu.switchlang]]
  name = "English"
  identifier = ""
  weight = 4
  url = "en"

[[Languages.eo.menu.switchlang]]
  name = "Français"
  identifier = ""
  weight = 4
  url = "fr"

[[Languages.eo.menu.switchlang]]
  name = "Nederlands"
  identifier = ""
  weight = 4
  url = "nl"

[[Languages.eo.menu.switchlang]]
  name = "Język polski"
  identifier = ""
  weight = 4
  url = "pl"

[[Languages.eo.menu.switchlang]]
  name = "繁體中文"
  identifier = ""
  weight = 4
  url = "zh-hant-tw"

[Languages.eo]
languageCode = "eo"
title = "JoinPeerTube"
weight = 1

[[Languages.eo.menu.main]]
name = "Demandoj"
identifier = "faq"
weight = 2
title = "FAQ"
url = "/eo/faq/"

[[Languages.eo.menu.main]]
name = "Apogo"
weight = 3
identifier = ""
url = "https://framacolibri.org/c/peertube"

[[Languages.eo.menu.main]]
name = "Dokumentado"
weight = 4
identifier = ""
url = "https://docs.joinpeertube.org/"

[[Languages.eo.menu.main]]
name = "Fontkodo"
weight = 4
identifier = ""
url = "https://github.com/Chocobozzz/PeerTube"

[[Languages.eo.menu.main]]
name = "Ekzemploj"
weight = 6
identifier = ""
url = "https://instances.joinpeertube.org"

[[Languages.eo.menu.main]]
name = "Honoro Rulo"
identifier = "hof"
weight = 7
title = "Honoro Rulo"
url = "/eo/hall-of-fame/"