[[Languages.fr.menu.switchlang]]
  name = "Deutsch"
  identifier = ""
  weight = 4
  url = "de"

[[Languages.fr.menu.switchlang]]
  name = "English"
  identifier = ""
  weight = 4
  url = "en"

[[Languages.fr.menu.switchlang]]
  name = "Nederlands"
  identifier = ""
  weight = 4
  url = "nl"

[Languages.fr]
languageCode = "fr"
title = "JoinPeerTube"
weight = 1

[[Languages.fr.menu.main]]
name = "FAQ"
identifier = "faq"
weight = 2
title = "FAQ"
url = "/fr/faq/"

[[Languages.fr.menu.main]]
name = "Support"
weight = 3
identifier = ""
url = "https://framacolibri.org/c/qualite/peertube"

[[Languages.fr.menu.main]]
name = "Documentation"
weight = 4
identifier = ""
url = "https://docs.joinpeertube.org/"

[[Languages.fr.menu.main]]
name = "Code source"
weight = 5
identifier = ""
url = "https://github.com/Chocobozzz/PeerTube"

[[Languages.fr.menu.main]]
name = "Instances"
weight = 6
identifier = ""
url = "https://instances.joinpeertube.org"

[[Languages.fr.menu.main]]
name = "Tableau d’honneur"
identifier = "hof"
weight = 7
title = "Tableau d’honneur"
url = "/fr/hall-of-fame/"
