[[Languages.nl.menu.switchlang]]
  name = "Deutsch"
  identifier = ""
  weight = 4
  url = "de"

[[Languages.nl.menu.switchlang]]
  name = "Français"
  identifier = ""
  weight = 4
  url = "fr"

[[Languages.nl.menu.switchlang]]
  name = "English"
  identifier = ""
  weight = 4
  url = "en"

[Languages.nl]
languageCode = "nl"
title = "JoinPeerTube"
weight = 1

[[Languages.nl.menu.main]]
name = "FAQ"
identifier = "faq"
weight = 2
title = "FAQ"
url = "/nl/faq/"

[[Languages.nl.menu.main]]
name = "Hulp"
weight = 3
identifier = ""
url = "https://framacolibri.org/c/peertube"

[[Languages.nl.menu.main]]
name = "Documentatie"
weight = 4
identifier = ""
url = "https://docs.joinpeertube.org/"

[[Languages.nl.menu.main]]
name = "Broncode"
weight = 5
identifier = ""
url = "https://github.com/Chocobozzz/PeerTube"

[[Languages.nl.menu.main]]
name = "Instanties"
weight = 6
identifier = ""
url = "https://instances.joinpeertube.org"

[[Languages.nl.menu.main]]
name = "Eregalerij"
identifier = "hof"
weight = 7
title = "Eregalerij"
url = "/nl/hall-of-fame/"
