[[Languages.pl.menu.switchlang]]
  name = "Deutsch"
  identifier = ""
  weight = 4
  url = "de"

[[Languages.pl.menu.switchlang]]
  name = "Esperanto"
  identifier = ""
  weight = 4
  url = "eo"

[[Languages.pl.menu.switchlang]]
  name = "Français"
  identifier = ""
  weight = 4
  url = "fr"

[[Languages.pl.menu.switchlang]]
  name = "Nederlands"
  identifier = ""
  weight = 4
  url = "nl"

[[Languages.pl.menu.switchlang]]
  name = "English"
  identifier = ""
  weight = 4
  url = "en"

[[Languages.pl.menu.switchlang]]
  name = "繁體中文"
  identifier = ""
  weight = 4
  url = "zh-hant-tw"

[Languages.pl]
languageCode = "pl"
title = "JoinPeerTube"
weight = 1

[[Languages.pl.menu.main]]
name = "Najczęściej zadawane pytania"
identifier = "faq"
weight = 2
title = "Najczęściej zadawane pytania"
url = "/pl/faq/"

[[Languages.pl.menu.main]]
name = "Wsparcie"
weight = 3
identifier = ""
url = "https://framacolibri.org/c/peertube"

[[Languages.pl.menu.main]]
name = "Dokumentacja"
weight = 4
identifier = ""
url = "https://docs.joinpeertube.org/"

[[Languages.pl.menu.main]]
name = "Kod źródłowy"
weight = 5
identifier = ""
url = "https://github.com/Chocobozzz/PeerTube"

[[Languages.pl.menu.main]]
name = "Instancje"
weight = 6
identifier = ""
url = "https://instances.joinpeertube.org"

[[Languages.pl.menu.main]]
name = "Sala sławy"
identifier = "hof"
weight = 7
title = "Sala sławy"
url = "/pl/hall-of-fame/"