[[Languages.zh-hant-tw.menu.switchlang]]
  name = "Deutsch"
  identifier = ""
  weight = 4
  url = "de"

[[Languages.zh-hant-tw.menu.switchlang]]
  name = "Esperanto"
  identifier = ""
  weight = 4
  url = "eo"

[[Languages.zh-hant-tw.menu.switchlang]]
  name = "Français"
  identifier = ""
  weight = 4
  url = "fr"

[[Languages.zh-hant-tw.menu.switchlang]]
  name = "Nederlands"
  identifier = ""
  weight = 4
  url = "nl"

[[Languages.zh-hant-tw.menu.switchlang]]
  name = "Język polski"
  identifier = ""
  weight = 4
  url = "pl"

[[Languages.zh-hant-tw.menu.switchlang]]
  name = "English"
  identifier = ""
  weight = 4
  url = "en"

[Languages.zh-hant-tw]
languageCode = "zh-hant-tw"
title = "JoinPeerTube"
weight = 1

[[Languages.zh-hant-tw.menu.main]]
name = "FAQ"
identifier = "faq"
weight = 2
title = "FAQ"
url = "/zh-hant-tw/faq/"

[[Languages.zh-hant-tw.menu.main]]
name = "支援"
weight = 3
identifier = ""
url = "https://framacolibri.org/c/peertube"

[[Languages.zh-hant-tw.menu.main]]
name = "文件"
weight = 4
identifier = ""
url = "https://docs.joinpeertube.org/"

[[Languages.zh-hant-tw.menu.main]]
name = "原始碼"
weight = 5
identifier = ""
url = "https://github.com/Chocobozzz/PeerTube"

[[Languages.zh-hant-tw.menu.main]]
name = "實體"
weight = 6
identifier = ""
url = "https://instances.joinpeertube.org"

[[Languages.zh-hant-tw.menu.main]]
name = "名人堂"
identifier = "hof"
weight = 7
title = "名人堂"
url = "/zh-hant-tw/hall-of-fame/"